### ISSUE TITLE
All the work logs are not displayed in the interface

### ISSUE THREAD

**Issue by sagarb2** [everit-org/jira-timetracker-plugin#253] opened 2016-06-09 05:25 UTC
There are 4 Work logs made on same issue by the same user but only 3 are displayed in the interface. 
Work logs on an issue:
1h; 30m; 2h; 3h
Work logs displayed in Timetracker interface:
30m; 1h; 3h
Table report and Chart report has the correct values and even in the interface, Summary for day has 6h 30m

![image](https://cloud.githubusercontent.com/assets/19823582/15919635/ce28ada6-2e30-11e6-8503-5ca3e7f1f900.png)

JIRA version: v6.4.11
Timetracker version: 2.4.1

Please resolve this issue at the earliest as we have implemented this plugin in Production

Thanks,
Sagar

**Comment by bordatesz** [comment] 2016-06-09 09:25
Hi there!
This is a strange behaviour. It seem the data is there, but the table did not render right.
- Is this also occurs for multiple users?
- Do you see this worklog on the Issue's Work Log screen?
- The entries include notes in the production system?
- Did you try it out with different browsers? (Maybe this is a JS error.)

**Comment by sagarb2** [comment] 2016-06-09 10:01
Hi,

Yes, the data is there but the table did not render it.

Is this also occurs for multiple users?
Yes
Do you see this worklog on the Issue's Work Log screen?
Yes
The entries include notes in the production system?
If you were asking about the notes mentioned while logging work then the answer is no. Please let me know if you are looking for other information
Did you try it out with different browsers? (Maybe this is a JS error.)
Just tried on Firefox and IE and the same issue is there

Just in case if it helps, all these work logs are overlapping. I have anyways seen instances where the work log was missing even when there was no overlap

**Comment by bordatesz** [comment] 2016-06-09 12:26
Unfortunately, we can not reproduce the problem, so if you do not mind, I ask a few more questions:
- Are these worklogs added by the Timetracker?
- What happens if you add worklog one after another? After which step is this entry disappearance happening?
- Did you use any other time tracking plugin in the past?
- Is the worklog allowed all users to view? (You can check this on the Issue Work Log screen. If there is a padlock icon in the worklog's header,  it's viewable only by members of a particular project role or group.)
- Can you check the browser's console if there's any error message?

**Comment by sagarb2** [comment] 2016-06-09 12:44
Hi,
- I saw this issue when I entered work logs using Timetracker and also when entered on Issue view page.
- It varies, sometimes I get this issue when I enter 4 records and sometimes 3 records
- We are using JIRA Timesheet Reports and Gadgets Plugin also
- Yes
- Below is the excerpt from the console. The display is set to none for the record which is not displayed

![image](https://cloud.githubusercontent.com/assets/19823582/15929945/c5ba9b2e-2e6d-11e6-8afe-f39b40a8b594.png)

**Comment by bordatesz** [comment] 2016-06-09 13:24
Based on your screenshot, something in your JIRA overwrite the global user agent stylesheet. We don't use inline style in Timetracker's table rows, but you have a "style=display: table-row" and the "none" in the table row tags. I attached a screenshot where you can see how it should look like. I highlited the style source, which in the optimal case is the 'user agent'. I suppose this is where you have a difference, and you can search for the root cause.
Just to be sure, did you intall Timetracker from the Atlassian Marketplace?

Note, that this could happen, because we didn't use the Atlassian stylesheet. This will not happen in the future, because we are already working on the new design, which is relies on the Atlassian style framework, just like the new Reporting.

![trglobal](https://cloud.githubusercontent.com/assets/5459077/15930992/fe064338-2e55-11e6-8ede-774a32de5651.PNG)

**Comment by sagarb2** [comment] 2016-06-09 13:43
Yes, I downloaded it from Atlassian Marketplace. When is the next release where you will be using Atlassian stylesheet?

**Comment by bordatesz** [comment] 2016-06-09 13:52
We plan to release the new design within one or two months.
Did you check what is overwriting the user agent stylesheet on the 'tr'? If this caused by an add-on, you can disable it and use Timetracker now.

**Comment by bordatesz** [comment] 2016-06-09 16:13
@sagarbarakam 
Sorry, it was invalid what I wrote above. Inline style cannot be added with outer stylesheet. This can be happen in two case: 1. Somebody modified our source code. 2. Something inject it with javascript. Now, in the latter case, this can be caused by many things: broswer plugin, your office IT settings, modified javascript somewhere, viruses, etc. Please test Timetracker with another PC, on your PC at home, on your phone, etc. to be sure.

**Comment by sagarb2** [comment] 2016-06-13 05:12
Hi, we were able to identify the root cause of this issue. It was because of another custom plugin which we have developed. When we disable that plugin we were able to see all the records in timetracker.

**Comment by bordatesz** [comment] 2016-06-13 09:21
Hi there!
I am glad that we managed to identify the problem! :) Be sure that your custom plugin does not overwrite any global style and it'll work. I'm going to close this issue, but feel free to repoen it or contact me if you have any further question!

**Closed as completed** 2016-06-13 09:22 UTC
Labels: bug, invalid
