### ISSUE TITLE
"Unparseable date" errors when using UK date format

### ISSUE THREAD

**Issue by asztal** [everit-org/jira-timetracker-plugin#298] opened 2016-07-10 20:47 UTC
Jó estét,

Apologies if I am doing something stupid here, but I'm having a problem when browsing to a specific date on the time tracker. I get an error viewing this URL: https://jira.thecompanyiworkfor.com/secure/JiraTimetrackerWebAction.jspa?dateFormatted=10/07/2016

This could be because I've changed the date format for JIRA's date pickers to be UK format. I think the changes I've made are correct though, because JIRA itself handles them fine.

My JIRA date format settings are:
**jira.date.picker.java.format:** dd/MM/yyyy
**jira.date.picker.javascript.format:** %d/%m/%Y
**jira.date.time.picker.java.format:** dd/MM/yyyy HH:mm
**jira.date.time.picker.javascript.format:** %d/%m/%Y %H:%M
**jira.lf.date.dmy:** dd/MM/yyyy

I followed [https://confluence.atlassian.com/jira/changing-the-due-date-input-format-192536.html](Atlassian's article on JIRA date formats) when setting them.

The error is:

```
java.text.ParseException: Unparseable date: "10/07/2016"
    at java.text.DateFormat.parse(Unknown Source)
    at org.everit.jira.timetracker.plugin.util.DateTimeConverterUtil.stringToDate(DateTimeConverterUtil.java:379)
    at org.everit.jira.timetracker.plugin.web.JiraTimetrackerWebAction.dateSwitcherAction(JiraTimetrackerWebAction.java:409)
    at org.everit.jira.timetracker.plugin.web.JiraTimetrackerWebAction.doExecute(JiraTimetrackerWebAction.java:528)
    at webwork.action.ActionSupport.execute(ActionSupport.java:165)
    at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:88)
    at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:39)
```

Note - I'm using v2.5.0 of this plugin because we're not using JIRA 7 yet.

Do you know if this is a problem with the plugin or the way I've configured JIRA?

**Comment by bordatesz** [comment] 2016-07-11 08:28
Hi there!

I don't think you did anything stupid. :) We'll look into this because it should work after date format change.

**Comment by bordatesz** [comment] 2016-07-12 09:42
Hello @asztal,

Unfortunately, we didn't able to reproduce the problem. With the same settings as yours, we didn't dedect any irregularity. 
Is this occours for one sepcial day, or Timetracker doesn't work at all?
Can you please reinstall the plugin and see if it's help?

**Comment by asztal** [comment] 2016-07-12 16:58
Thanks for your response, I'll try reinstalling the plugin.

It seems to be any day. I can only look at my time entries for today because the "formattedDate" query parameter is not set when you first open the time tracker.

Here's the form data sent (when I clicked the ">" button):
date:12/07/2016 
dayNext:>
endOrDuration:end
startTime:18:03
endTime:17:43
comments:

And in another instance (I selected a date on the calendar): 
date:29/07/2016 
datesubmit:Submit
endOrDuration:end
startTime:18:03
endTime:17:49
comments:

In both cases the URL has "?dateFormatted=12/07/2016" at the end.

**Comment by asztal** [comment] 2016-07-12 16:59
My user profile has the locale set to "English (UK)", if that's any help. I tried some others but it made no difference.

**Comment by bordatesz** [comment] 2016-07-19 10:38
Hello @asztal!

Is this problem still exists? We tried several ways, but we weren't able to reproduce the problem. I suspect that the source of the problem is not the Timetracker.

**Comment by asztal** [comment] 2016-07-19 12:01
It's still happening for me, yes (I did try re-installing the plugin, but it made no difference). If I had all the time in the world, I would set up a development version of JIRA and see if I can replicate it. As it is, I doubt that I will have enough time to investigate this in that level of detail.

If you want to close this issue or mark it as low priority, go ahead - I have a sort-of workaround for now. (If I need to look at my timesheet for yesterday or last week, the Table Report tab seems to work well enough).

Thanks for your efforts, I appreciate your help! Your plugin is still very useful to me and my colleagues.

**Comment by bordatesz** [comment] 2016-07-19 12:42
I'm glad to hear that it's still useful to you, and I'm sorry we weren't able to solve this issue. If any other user will report this, or we make some progress, I will notify you immediately.

**Comment by bordatesz** [comment] 2016-10-06 10:57
Hi there!
Sorry for the late update. This is possibly fixed in the latest release: [3.2.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v3.2.0), [2.6.0](https://github.com/everit-org/jira-timetracker-plugin/releases/tag/v2.6.0)

**Closed as completed by bordatesz** 2016-10-06 10:57 UTC
Labels: bug

**Comment by asztal** [comment] 2016-10-06 11:49
It certainly seems so! Thanks so much for your great work. I love the new user interface too.

**Comment by bordatesz** [comment] 2016-10-06 12:16
I'm happy to hear that! :)
